BackOffice/BackOffice-COCO-TRIP/Controllers/M8_LocalidadController.cs
using BackOffice_COCO_TRIP.Datos.Entidades;
using BackOffice_COCO_TRIP.Negocio.Comandos;
using BackOffice_COCO_TRIP.Negocio.Fabrica;
using System;
using System.Web.Mvc;

namespace BackOffice_COCO_TRIP.Controllers
{
  /// <summary>
  /// Clase encargada de la lógica de la interfaz de Localidades.
  /// </summary>
  public class M8_LocalidadController : Controller
  {

    /// <summary>
    /// Controlador de la vista Index.
    /// </summary>
    /// <returns>Menu principal de Localidades</returns>
    public ActionResult Index()
    {
      ViewBag.Title = "Localidades de los Eventos";
      Comando comando = FabricaComando.GetComandoConsultarLocalidades();
      comando.Execute();
      TempData["listaLocalidadEvento"] = comando.GetResult();
      return View(comando.GetResult()[0]);
    }

    /// <summary>
    /// Controlador de la vista Details.
    /// </summary>
    /// <param name="id"> id de la localidad a detallar</param>
    /// <returns>Vista de la localidad a detallar</returns>
    public ActionResult Details(int id)
    {
      return View();
    }

    /// <summary>
    /// Controlador para cargar la vista Create.
    /// </summary>
    /// <returns>Vista Create</returns>
    public ActionResult Create()
    {
      return View();
    }

    /// <summary>
    /// Controlador de la vista Create al momento de realizar un submit dentro de la misma.
    /// </summary>
    /// <param name="localidad"> localidad a crear</param>
    /// <returns>Vista Create</returns>
    [HttpPost]
    public ActionResult Create(Localidad localidad)
    {
      if (ModelState.IsValid)
      {
        Comando comando = FabricaComando.GetComandoAgregarLocalidad();
        comando.SetPropiedad(localidad);
        comando.Execute();
        ModelState.AddModelError(string.Empty, (String)comando.GetResult()[0]);
      }
      return View();
    }

    /// <summary>
    /// Controlador que carga la vista Edit.
    /// </summary>
    /// <param name="id">id de la localidad a editar</param>
    /// <returns>Vista Edit</returns>
    public ActionResult Edit(int id)
    {
      ViewBag.Title = "Editar Localidad";
      Comando comando = FabricaComando.GetComandoConsultarLocalidad();
      comando.SetPropiedad(id);
      comando.Execute();
      ModelState.AddModelError(string.Empty, (String)comando.GetResult()[1]);
      return View(comando.GetResult()[0]);

    }

    /// <summary>
    /// Controlador da vista Edit una vez realizado un submit dentro de la misma.
    /// </summary>
    /// <param name="localidad">localidad a editar</param>
    /// <returns> Vista Index</returns>
    [HttpPost]
    public ActionResult Edit(Localidad localidad)
    {
      if (ModelState.IsValid)
      {
        Comando comando = FabricaComando.GetComandoModificarLocalidad();
        comando.SetPropiedad(localidad);
        comando.Execute();
        ModelState.AddModelError(string.Empty, (String)comando.GetResult()[0]);
      }
      return View();
    }

    /// <summary>
    /// Controlador de la vista Delete.
    /// </summary>
    /// <param name="id">Identificador único de la localidad</param>
    /// <param name="collection"> Colección del formulario</param>
    /// <returns>Vista Index</returns>
    public ActionResult Delete(int id, FormCollection collection)
    {
      ViewBag.Title = "Localidades de los Eventos";
      Comando comando = FabricaComando.GetComandoEliminarLocalidad();
      comando.SetPropiedad(id);
      comando.Execute();
      ModelState.AddModelError(string.Empty, (String)comando.GetResult()[0]);
      return RedirectToAction("Index");



    }

    /// <summary>
    /// Controlador de la vista Select.
    /// </summary>
    /// <param name="id">Identificador único de la Localidad a consultar</param>
    /// <returns>Vista Select</returns>
    public ActionResult Select(int id)
    {
      ViewBag.Title = "Consultar Localidad";
      Comando comando = FabricaComando.GetComandoConsultarLocalidad();
      comando.SetPropiedad(id);
      comando.Execute();

      ModelState.AddModelError(string.Empty, (String)comando.GetResult()[1]);
      return View(comando.GetResult()[0]);

    }
  }
}

BackOffice/BackOffice-COCO-TRIP/Views/M8_Localidad/Create.cshtml
@Styles.Render("~/bundles/lugares_addCSS")
@model BackOffice_COCO_TRIP.Datos.Entidades.Localidad

@{
    ViewBag.Title = "Localidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Localidad </h2>

@using (Html.BeginForm("Create", "M8_Localidad", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal" }))
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-5">
        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nombre, null, new { @class = "label label-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Descripcion, null, new { @class = "label label-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Coordenadas, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-5">
        @Html.EditorFor(model => model.Coordenadas, new { htmlAttributes = new { @class = "disabledClass", @id = "coords" } })
        @Html.ValidationMessageFor(model => model.Coordenadas, null, new { @class = "label label-danger" })
      </div>
      <div id="map" class="text-center"></div>
    </div>


    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Crear Localidad" class="btn btn-default" />
      </div>
    </div>
  </div>
}


@section scripts {
  @Scripts.Render("~/bundles/Localidad_insert-coordsJS")
  @Scripts.Render("https://maps.googleapis.com/maps/api/js?key=AIzaSyBLZJfuHODaUCPcVW8GwMW6nCXcm3SldgY&callback=initMap")
}

BackOffice/BackOffice-COCO-TRIP/Views/M8_Localidad/Edit.cshtml
@Styles.Render("~/bundles/lugares_addCSS")
@Styles.Render("~/bundles/lugares_modifyCSS")
@model BackOffice_COCO_TRIP.Datos.Entidades.Localidad

@{
    ViewBag.Title = "Localidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Modificar Localidad</h2>

@using (Html.BeginForm("Edit", "M8_Localidad", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal" }))
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Coordenadas, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Coordenadas, new { htmlAttributes = new { @class = "disabledClass", @id = "coords" } })
        @Html.ValidationMessageFor(model => model.Coordenadas, "", new { @class = "text-danger" })
      </div>
      <div id="map" class="text-center"></div>
    </div>


    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Update" class="btn btn-default" />
      </div>
    </div>
  </div>


  @section scripts {
    @Scripts.Render("~/bundles/Localidad_insert-coordsJS")
    @Scripts.Render("https://maps.googleapis.com/maps/api/js?key=AIzaSyBLZJfuHODaUCPcVW8GwMW6nCXcm3SldgY&callback=initMap")
  }
}

BackOffice/BackOffice-COCO-TRIP/Views/M8_Localidad/Index.cshtml
@model IEnumerable<BackOffice_COCO_TRIP.Datos.Entidades.Localidad>

@{
    ViewBag.Title = "Localidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css ">
<h2>Lista de Localidades</h2>
<div class="loader" id="loader"></div>
<div class="fondo-opaco" id="fondo-opaco"></div>
<div class="card">
  <div class="container-fluid pad-top">
    <div>@Html.ValidationSummary(true, "", new { @class = "text-danger" })</div>
    <table width="100" class="table table-striped table-bordered" id="example" cellspacing="0">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Descripci&oacute;n</th>

          <th>Opciones</th>

        </tr>
      </thead>
      <tbody>
        @foreach (var item in Model)
        {
          <tr>

            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
            <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>


            <td>
              <a class="btn btn-default circle" href="@Url.Action("Delete", "M8_Localidad", new { id = item.Id })" data-toggle="tooltip"
                 data-placement="top" title="Eliminar Localidad">
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
              </a>
              <a class="btn btn-default circle" href="@Url.Action("Select", "M8_Localidad", new { id = item.Id })" data-toggle="tooltip"
                 data-placement="top" title="Ver Localidad">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              </a>

              <a class="btn btn-default circle" href="@Url.Action("Edit", "M8_Localidad", new { id = item.Id })" data-toggle="tooltip"
                 data-placement="top" title="Editar">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
              </a>

            </td>

          </tr>
        }
      </tbody>
    </table>
  </div>
</div>

BackOffice/BackOffice-COCO-TRIP/Views/M8_Localidad/Select.cshtml
@model BackOffice_COCO_TRIP.Datos.Entidades.Localidad

@{
    ViewBag.Title = "Localidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Consultar Localidad</h2>


<div class="form-horizontal">
  <hr />

  <div class="form-group">
    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
      @Html.DisplayFor(model => model.Nombre, "nombre")
    </div>
  </div>

  <div class="form-group">
    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
      @Html.DisplayFor(model => model.Descripcion)
    </div>
  </div>

  <div class="form-group">
    @Html.LabelFor(model => model.Coordenadas, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
      @Html.DisplayFor(model => model.Coordenadas)
    </div>

  </div>

</div>