BackOffice/BackOffice-COCO-TRIP/Controllers/CategoriesController.cs
using BackOffice_COCO_TRIP.Datos.Entidades;
using BackOffice_COCO_TRIP.Negocio.Fabrica;
using BackOffice_COCO_TRIP.Negocio.Comandos;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BackOffice_COCO_TRIP.Comun;

namespace BackOffice_COCO_TRIP.Controllers
{
  public class CategoriesController : Controller
  {
    private Comando com;
    private ValidacionString validacion = new ValidacionString();
    /// <summary>
    /// Metodo que nos permite obtener la lista de las categorias
    ///mediante peticiones al servicio web a la hora de cargar
    /// </summary>
    // GET: Categories
    public ActionResult Index(int id = -1)
    {
      ViewBag.Title = "Categorías";
      IList<Categoria> listCategories = null;
      com = FabricaComando.GetComandoConsultarListaCategoria();
      com.SetPropiedad(id);
      com.Execute();
      JObject respuestaCategoria = (JObject)com.GetResult()[0];

      if (respuestaCategoria.Property("data") != null)
      {
        listCategories = respuestaCategoria["data"].ToObject<List<Categoria>>();
      }
      else
      {
        listCategories = new List<Categoria>();
        ModelState.AddModelError(string.Empty,
          "Ocurrio un error durante la comunicacion, revise su conexion a internet");
      }
      TempData["listaCategorias"] = listCategories;
      return View(listCategories);

    }


    /// <summary>
    /// Metodo que carga la pagina de creacion de categoria
    /// </summary>
    // GET: Categories/Create
    public ActionResult Create()
    {
      ViewBag.Title = "Agregar Categoría";
      Categoria categories = null;
      ConsultarCategoriasSelectCreate();
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite crear una nueva categoria mediante peticiones al servicio web
    /// </summary>
    // POST: Categories/Create
    [HttpPost]
    public ActionResult Create(Categoria categories)
    {
      ModelState.Remove("UpperCategories");
      if (ModelState.IsValid && ValidarName(categories.Name) && ValidarDescription(categories.Description))
      {
        string[] idNivel = Request["Categoria superior"].ToString().Split('-');
        categories.UpperCategories = Int32.Parse(idNivel[0]);
        categories.Nivel = Int32.Parse(idNivel[1]) + 1;
        com = FabricaComando.GetComandoAgregarCategoria();
        com.SetPropiedad(categories);
        com.Execute();
        JObject respuesta = (JObject)com.GetResult()[0];
        if (respuesta.Property("data") != null)
        {
          return RedirectToAction("Index");
        }
        ValidarError(respuesta);
      }
      ConsultarCategoriasSelectCreate();
      ViewBag.Title = "Agregar Categoría";
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite obtener lista de categorias a la cual se va a editar mediante peticiones al servicio web
    /// </summary>
    // GET: Categories/Edit/5
    public ActionResult Edit(int id)
    {
        ViewBag.Title = "Editar Categoría";
        ConsultarCategoriasSelectEdit(id);
        Categoria categories = null;
        com = FabricaComando.GetComandoConsultarCategoriaPorId();
        com.SetPropiedad(id);
        com.Execute();
        JObject respuestaCategoria = (JObject)com.GetResult()[0];
        if (respuestaCategoria.Property("data") != null)
        {
          categories =
            (respuestaCategoria["data"].HasValues ? respuestaCategoria["data"][0].ToObject<Categoria>() : null) ;
          if (categories == null)
          {
            return RedirectToAction("Index");
          }
        }
        else
        {
          ModelState.AddModelError(string.Empty,
            "Ocurrio un error durante la comunicacion, revise su conexion a internet");
        }
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite editar una nueva categoria existente mediante peticiones al servicio web
    /// </summary>
    // POST: Categories/Edit/5
    [HttpPost]
    public ActionResult Edit(int id, Categoria categories)
    {
      ModelState.Remove("Id");
      ModelState.Remove("UpperCategories");
      if (ModelState.IsValid && ValidarName(categories.Name) && ValidarDescription(categories.Description))
      {
        var idNivel = Request["Mover a la categoria"].ToString().Split('-');
        categories.UpperCategories = Int32.Parse(idNivel[0]);
        categories.Nivel = Int32.Parse(idNivel[1]) + 1;
        com = FabricaComando.GetComandoModificarCategoria();
        com.SetPropiedad(categories);
        com.Execute();
        JObject respuesta = (JObject)com.GetResult()[0];
        if (respuesta.Property("data") != null)
        {
          return RedirectToAction("Index");
        }
        ValidarError(respuesta);
      }

      ConsultarCategoriasSelectEdit(id);
      ViewBag.Title = "Editar Categoría";
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite cambiar el status de una categoria mediante peticiones al servicio web
    /// </summary>
    [HttpPost]
    public ActionResult ChangeStatus(Categoria categories)
    {
      com = FabricaComando.GetComandoEstadoCategoria();
      com.SetPropiedad(categories);
      com.Execute();
      JObject respuesta = (JObject)com.GetResult()[0];
      return Json(respuesta);
    }


    // ######################## Metodos Auxiliares ########################
    private void ConsultarCategoriasSelectCreate()
    {
      com = FabricaComando.GetComandoConsultarCategoriaSelect();
      com.Execute();
      var listaCategorias = (List<Categoria>)com.GetResult()[0];
      if (listaCategorias != null)
      {
        listaCategorias = listaCategorias.Where(s => s.Nivel < 3).ToList();
        ViewBag.MyList = listaCategorias;
      }
      else
      {
        listaCategorias = new List<Categoria>();
        ViewBag.MyList = listaCategorias;
        ModelState.AddModelError(string.Empty,
          "Ocurrio un error cargando las categorias, revise su conexion a internet");
      }

    }

    private void ConsultarCategoriasSelectEdit(int id)
    {
      com = FabricaComando.GetComandoConsultarCategoriaSelect();
      com.Execute();
      var listaCategoriasSelect = (List<Categoria>)com.GetResult()[0];
      if (listaCategoriasSelect != null)
      {
        listaCategoriasSelect = listaCategoriasSelect.Where(s => s.Nivel < 3 && s.Id != id).ToList();
        ViewBag.MyList = listaCategoriasSelect;
      }
      else
      {
        listaCategoriasSelect = new List<Categoria>();
        ViewBag.MyList = listaCategoriasSelect;
        ModelState.AddModelError(string.Empty,
          "Ocurrio un error cargando las categorias, revise su conexion a internet");
      }
    }

    // ############## Metodos para Validaciones de Vistas #################
    /// <summary>
    /// Metodo que nos permite validar si el nombre existe antes de agregar
    /// </summary>
    private void ValidarError(JObject respuesta)
    {
      if (respuesta.Property("MensajeError") != null)
      {
        ModelState.AddModelError(string.Empty, respuesta["MensajeError"].ToString());
      }
      else
      {
        ModelState.AddModelError(string.Empty, "Ocurrió un error de comunicación");
      }
    }

    private bool ValidarName(String input)
    {
      if (validacion.ValidarCaracteresEspeciales(input) && validacion.ValidarLongitudInputNombreCategoria(input))
      {
        return true;
      }
      ModelState.AddModelError(string.Empty,
        "El nombre de la categoria debe tener al menos 5 caracteres y máximo 20. Sólo se permiten letras.");
      return false;
    }

    private bool ValidarDescription(String input)
    {
      if (validacion.ValidarCaracteresEspeciales(input) && validacion.ValidarLongitudInputDescripcionCategoria(input))
      {
        return true;
      }
      ModelState.AddModelError(string.Empty,
        "La descripcion de la categoria debe tener al menos 5 caracteres y máximo 100. Sólo se permiten letras.");
      return false;
    }
  }
}

BackOffice/BackOffice-COCO-TRIP/Controllers/LugaresController.cs
using BackOffice_COCO_TRIP.Datos.Entidades;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using BackOffice_COCO_TRIP.Negocio.Comandos;
using BackOffice_COCO_TRIP.Negocio.Fabrica;
using Newtonsoft.Json.Linq;

namespace BackOffice_COCO_TRIP.Controllers
{
    /// <summary>
    /// Clase controlador de los Views de Lugares Turisticos
    /// </summary>
    public class LugaresController : Controller
    {
    
    private Comando com;
    private IList<Categoria> _categorias;

    // GET:Lugares
    public ActionResult Index()
    {
      ViewBag.Title = "Lugares Turísticos";
      return View();
    }

        // GET:Lugares/Details/5
    public ActionResult Details(int id)
    {
      return View();
    }

    /// <summary>
    /// Metodo GET que se dispara al acceder a la pantalla Create
    /// </summary>
    /// <returns></returns>
    /// GET:Lugares/Create
    public ActionResult Create()
    {
      JObject respuestaCategoria;
      ViewBag.Title = "Agregar Lugar Turístico";
      List<Categoria> listCategories = new List<Categoria>() ;

      
      com = FabricaComando.GetComandoConsultarCategoriaHabilitada();
      com.Execute();
      respuestaCategoria = (JObject)com.GetResult()[0];
      if (respuestaCategoria.Property("data")!= null)
      {

        listCategories = respuestaCategoria["data"].ToObject<List<Categoria>>();
        _categorias = listCategories;
        ViewBag.Categoria = _categorias;

      }
      else
      {

        ViewBag.Categoria = new List<Categoria>();

      }

      return View();
    }

        // POST:Lugares/Create
        /// <summary>
        /// Metodo POST que se dispara al insertar un lugar turistico
        /// </summary>
        /// <param name="lugar">Lugar Turistico</param>
        /// <returns></returns>
    [HttpPost]
    public ActionResult Create(LugarTuristico lugar)
    {

      com = FabricaComando.GetComandoAgregarLugarTuristico();
      LlenadoLugarTuristico();
      com.Execute();
      return RedirectToAction("ViewAll");

    }

    [HttpPost]
    public ActionResult Modify(LugarTuristico lugar)
    {
      com = FabricaComando.GetComandoModificarLugarTuristico();
      LlenadoLugarTuristico();
      com.SetPropiedad(Request.Form["Id"]);
      com.Execute();
      return RedirectToAction("ViewAll");
    }

        // GET:Lugares/Modify
        public ActionResult Modify(int id)
        {
      ViewBag.Title = "Modificar Lugar Turistico";
          JObject respuesta;
          com = FabricaComando.GetComandoConsultarLugarTuristico();
          com.SetPropiedad(id);
          com.Execute();
          respuesta = (JObject)com.GetResult()[0];
          var lugarTuristico = respuesta["data"].ToObject<LugarTuristico>();
          return View(lugarTuristico);
        }

      
        // GET:Lugares/DetailLugar
        /// <summary>
        /// Metodo GET que se dispara al acceder a la pantalla detalle de lugar turistico
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
    public ActionResult LugarDetail(int id)
    {

      JObject respuesta;
      ViewBag.Title = "Detalle de Actividad";
      com = FabricaComando.GetComandoConsultarLugarTuristico();
      com.SetPropiedad(id);
      com.Execute();
      respuesta  = (JObject)com.GetResult()[0];
      var lugarTuristico = respuesta["data"].ToObject<LugarTuristico>();
      return View(lugarTuristico);

     }

      
    //Pantalla ver todos los lugares turisticos

    // GET:Lugares/ViewAll
    /// <summary>
    /// Metodo GET que se dispara al acceder a la pantalla de ver todos los lugares turisticos (ViewAll)
    /// </summary>
    /// <returns>View</returns>
    public ActionResult ViewAll()
    {
      JObject respuesta;
      ViewBag.Title = "Lugares Turísticos";
      com = FabricaComando.GetComandoConsultarLugaresTuristicos();
      com.Execute();
      respuesta = (JObject)com.GetResult()[0];
      List<LugarTuristico> _lugaresTuristicos = respuesta["data"].ToObject<List<LugarTuristico>>();
      return View(_lugaresTuristicos);
    }
     


     // PUT:Lugares/ViewAll?id={0}&activar={1}
     /// <summary>
     /// Metodo PUT que se dispara al cambiar el estado de un lugar turistico
     /// </summary>
     /// <param name="id">Id del lugar turistico</param>
     /// <param name="activar">Estado del lugar turistico</param>
     /// <returns></returns>
    [HttpPost]
    public ActionResult ViewAll(int id, bool activar)
    {
      com = FabricaComando.GetComandoActualizarEstadoLugarTuristico();
      com.SetPropiedad(id);
      com.SetPropiedad(activar);
      com.Execute();

      JObject respuesta;
      ViewBag.Title = "Lugares Turísticos";
      com = FabricaComando.GetComandoConsultarLugaresTuristicos();
      com.Execute();
      respuesta = (JObject)com.GetResult()[0];
      List<LugarTuristico> _lugaresTuristicos = respuesta["data"].ToObject<List<LugarTuristico>>();
      return View(_lugaresTuristicos);

    }

        //

        // GET:Lugares/Activate/5
        public ActionResult Activate(int id)
        {
            return View();
        }

        // POST:Lugares/Activate/5
        [HttpPost]
        public ActionResult Activate(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET:Lugares/PageDown
        public ActionResult PageDown()
        {
          ViewBag.Title = "Lugares Turísticos";

          return View();
        }

    public void LlenadoLugarTuristico()
    {
      //Seteando la foto    
      com.SetPropiedad (Request.Form["fotoLugar"]);

      //Seteando el nombre
      com.SetPropiedad(Request.Form["Nombre"]);

      //Seteando el costo
      Double.TryParse(Request.Form["Costo"], out double costo);
      com.SetPropiedad(costo);

      //Seteando el status
      com.SetPropiedad(Request.Form["activar"]);
      
      //Seteando las categorias
      for (int i=0; i <= 3; i++)
      {

        com.SetPropiedad(String.Format("{0}", Request.Form["categoria_"+i]));       
       
      }

      //Seteando los horarios
      for(int i = 0; i <= 6; i++)
      {

        com.SetPropiedad( Request.Form["dia_"+i]);
        com.SetPropiedad( Request.Form["Horario["+i+"].HoraApertura"]);
        com.SetPropiedad( Request.Form["Horario[" + i + "].HoraCierre"]);
        
      }

      //Seteando las actividades
      for (int i = 0; i <= 3; i++)
      {
        com.SetPropiedad(Request.Form["Actividad[" + i + "].Activar"]);
        com.SetPropiedad(Request.Form["fotoActividad_" + i ]);
        com.SetPropiedad(Request.Form["Actividad[" + i + "].Nombre"]);
        com.SetPropiedad(Request.Form["Actividad[" + i + "].Descripcion"]);
        com.SetPropiedad(Request.Form["Actividad[" + i + "].Duracion"]);
      }

      //Seteando los ultimos parametros

      com.SetPropiedad(Request.Form["Direccion"]);
      com.SetPropiedad(Request.Form["Correo"]);
      com.SetPropiedad(Request.Form["Telefono"]);
      com.SetPropiedad(Request.Form["Descripcion"]);
      com.SetPropiedad(Request.Form["Latitud"]);
      com.SetPropiedad(Request.Form["Longitud"]);

      
    }


   

    }
}

BackOffice/BackOffice-COCO-TRIP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="@Url.Content("~/Images/logo_cocotrip.png")" />
  <title>@ViewBag.Title - COCOTRIP</title>

  <!-- GOOGLE FONTS -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <!-- GOOGLE FONTS-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
  @Styles.Render("~/Content/css")
  @Styles.Render("~/bundles/sweetAlertCSS")
  @Scripts.Render("~/bundles/modernizr")
</head>
<body>



  <div id="wrapper">

    <div class="container-fluid">
      <div class="row">
        <div class="col-3">
          <!-- /. NAV TOP  -->
          <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
              <ul class="nav" id="main-menu">

                <div class="logo-sidebar" align="center">
                  <img src="@Url.Content("~/Images/logo_sidebar.png")" alt="">
                </div>

                <li class="active">
                  <a href="@Url.Action("Index", "Home")"><i class="fa fa-desktop "></i>Dashboard</a>
                </li>

                <li data-toggle="collapse" data-target="#products" class="collapsed active">
                  <a href="#"><i class="fa fa-map-o" aria-hidden="true"></i> Lugar Tur&iacute;stico <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="products">
                  <li class="active"><a href="@Url.Action("ViewAll", "Lugares")"><i class="fa fa-eye icon-see-sidebar" aria-hidden="true"></i>Ver Todos</a></li>
                  <li><a href="@Url.Action("Create", "Lugares")"><i class="fa fa-plus icon-add-sidebar" aria-hidden="true"></i>Agregar</a></li>
                </ul>
                <li data-toggle="collapse" data-target="#categoriesOption" class="collapsed active">
                  <a href="#"><i class="fa fa-sort-amount-desc" aria-hidden="true"></i>Categor&iacute;as</a>
                </li>
                <ul class="sub-menu collapse sideItem" id="categoriesOption">
                  <li><a href="@Url.Action("Create", "Categories")"><i class="fa fa-plus icon-add-sidebar" aria-hidden="true"></i>Agregar</a></li>
                  <li class="active"><a href="@Url.Action("Index", "Categories", new { id = "" })"><i class="fa fa-eye icon-see-sidebar" aria-hidden="true"></i>Ver Categor&iacute;as</a></li>
                </ul>

                <li data-toggle="collapse" data-target="#localidadesEventosOption" class="collapsed active">
                  <a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i>Localidades</a>
                </li>
                <ul class="sub-menu collapse sideItem" id="localidadesEventosOption">
                  <li><a href="@Url.Action("Create", "M8_Localidad")"><i class="fa fa-plus icon-add-sidebar" aria-hidden="true"></i>Agregar</a></li>
                  <li class="active"><a href="@Url.Action("Index", "M8_Localidad")"><i class="fa fa-eye icon-see-sidebar" aria-hidden="true"></i>Ver Todos</a></li>
                </ul>

                <li data-toggle="collapse" data-target="#eventsOption" class="collapsed active">
                  <a href="#"><i class="fa fa-star" aria-hidden="true"></i>Eventos</a>
                </li>
                <ul class="sub-menu collapse sideItem" id="eventsOption">
                  <li><a href="@Url.Action("Create", "M8Events")"><i class="fa fa-plus icon-add-sidebar" aria-hidden="true"></i>Agregar</a></li>
                  <li class="active"><a href="@Url.Action("Index", "M8Events")"><i class="fa fa-eye icon-see-sidebar" aria-hidden="true"></i>Ver Todos</a></li>
                </ul>
              </ul>
            </div>

          </nav>
          <!-- /. NAV SIDE  -->
        </div>

        <div class="col-9">
          <div id="page-wrapper">
            <div id="page-inner">

              <div class="content-page">
                <div class="row">
                  <div class="headline card">
                    <h4 class="tittle">
                      @ViewBag.Title
                    </h4>
                  </div>
                </div>
                <!-- aqui -->
                <div class="row" style="margin-top: 5%;">
                  <!-- o aqui -->
                  @RenderBody()
                </div>
              </div>

            </div>
            <!-- /. PAGE INNER  -->
          </div>
          <!-- /. PAGE WRAPPER  -->
        </div>

      </div>
    </div>

  </div>
  <div class="footer">
    <div class="row">
      <div class="col-lg-12">
        &copy; @DateTime.Now.Year - Mi aplicaci&oacute;n ASP.NET
      </div>
    </div>
  </div>






  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  @Scripts.Render("~/bundles/bootstrap")
  @Scripts.Render("~/bundles/customJS")
  @Scripts.Render("~/bundles/sweetAlertJS")
  @RenderSection("scripts", required: false)


</body>

</html>