BackOffice/BackOffice-COCO-TRIP/Controllers/CategoriesController.cs
using BackOffice_COCO_TRIP.Datos.Entidades;
using BackOffice_COCO_TRIP.Negocio.Fabrica;
using BackOffice_COCO_TRIP.Negocio.Comandos;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BackOffice_COCO_TRIP.Comun;

namespace BackOffice_COCO_TRIP.Controllers
{
  public class CategoriesController : Controller
  {
    private Comando com;
    private ValidacionString validacion = new ValidacionString();
    /// <summary>
    /// Metodo que nos permite obtener la lista de las categorias
    ///mediante peticiones al servicio web a la hora de cargar
    /// </summary>
    // GET: Categories
    public ActionResult Index(int id = -1)
    {
      ViewBag.Title = "Categorías";
      IList<Categoria> listCategories = null;
      com = FabricaComando.GetComandoConsultarListaCategoria();
      com.SetPropiedad(id);
      com.Execute();
      JObject respuestaCategoria = (JObject)com.GetResult()[0];

      if (respuestaCategoria.Property("data") != null)
      {
        listCategories = respuestaCategoria["data"].ToObject<List<Categoria>>();
      }
      else
      {
        listCategories = new List<Categoria>();
        ModelState.AddModelError(string.Empty,
          "Ocurrio un error durante la comunicacion, revise su conexion a internet");
      }
      TempData["listaCategorias"] = listCategories;
      return View(listCategories);

    }


    /// <summary>
    /// Metodo que carga la pagina de creacion de categoria
    /// </summary>
    // GET: Categories/Create
    public ActionResult Create()
    {
      ViewBag.Title = "Agregar Categoría";
      Categoria categories = null;
      ConsultarCategoriasSelectCreate();
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite crear una nueva categoria mediante peticiones al servicio web
    /// </summary>
    // POST: Categories/Create
    [HttpPost]
    public ActionResult Create(Categoria categories)
    {
      ModelState.Remove("UpperCategories");
      if (ModelState.IsValid && ValidarName(categories.Name) && ValidarDescription(categories.Description))
      {
        string[] idNivel = Request["Categoria superior"].ToString().Split('-');
        categories.UpperCategories = Int32.Parse(idNivel[0]);
        categories.Nivel = Int32.Parse(idNivel[1]) + 1;
        com = FabricaComando.GetComandoAgregarCategoria();
        com.SetPropiedad(categories);
        com.Execute();
        JObject respuesta = (JObject)com.GetResult()[0];
        if (respuesta.Property("data") != null)
        {
          return RedirectToAction("Index");
        }
        ValidarError(respuesta);
      }
      ConsultarCategoriasSelectCreate();
      ViewBag.Title = "Agregar Categoría";
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite obtener lista de categorias a la cual se va a editar mediante peticiones al servicio web
    /// </summary>
    // GET: Categories/Edit/5
    public ActionResult Edit(int id)
    {
        ViewBag.Title = "Editar Categoría";
        ConsultarCategoriasSelectEdit(id);
        Categoria categories = null;
        com = FabricaComando.GetComandoConsultarCategoriaPorId();
        com.SetPropiedad(id);
        com.Execute();
        JObject respuestaCategoria = (JObject)com.GetResult()[0];
        if (respuestaCategoria.Property("data") != null)
        {
          categories =
            (respuestaCategoria["data"].HasValues ? respuestaCategoria["data"][0].ToObject<Categoria>() : null) ;
          if (categories == null)
          {
            return RedirectToAction("Index");
          }
        }
        else
        {
          ModelState.AddModelError(string.Empty,
            "Ocurrio un error durante la comunicacion, revise su conexion a internet");
        }
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite editar una nueva categoria existente mediante peticiones al servicio web
    /// </summary>
    // POST: Categories/Edit/5
    [HttpPost]
    public ActionResult Edit(int id, Categoria categories)
    {
      ModelState.Remove("Id");
      ModelState.Remove("UpperCategories");
      if (ModelState.IsValid && ValidarName(categories.Name) && ValidarDescription(categories.Description))
      {
        var idNivel = Request["Mover a la categoria"].ToString().Split('-');
        categories.UpperCategories = Int32.Parse(idNivel[0]);
        categories.Nivel = Int32.Parse(idNivel[1]) + 1;
        com = FabricaComando.GetComandoModificarCategoria();
        com.SetPropiedad(categories);
        com.Execute();
        JObject respuesta = (JObject)com.GetResult()[0];
        if (respuesta.Property("data") != null)
        {
          return RedirectToAction("Index");
        }
        ValidarError(respuesta);
      }

      ConsultarCategoriasSelectEdit(id);
      ViewBag.Title = "Editar Categoría";
      return View(categories);
    }

    /// <summary>
    /// Metodo que nos permite cambiar el status de una categoria mediante peticiones al servicio web
    /// </summary>
    [HttpPost]
    public ActionResult ChangeStatus(Categoria categories)
    {
      com = FabricaComando.GetComandoEstadoCategoria();
      com.SetPropiedad(categories);
      com.Execute();
      JObject respuesta = (JObject)com.GetResult()[0];
      return Json(respuesta);
    }


    // ######################## Metodos Auxiliares ########################
    private void ConsultarCategoriasSelectCreate()
    {
      com = FabricaComando.GetComandoConsultarCategoriaSelect();
      com.Execute();
      var listaCategorias = (List<Categoria>)com.GetResult()[0];
      if (listaCategorias != null)
      {
        listaCategorias = listaCategorias.Where(s => s.Nivel < 3).ToList();
        ViewBag.MyList = listaCategorias;
      }
      else
      {
        listaCategorias = new List<Categoria>();
        ViewBag.MyList = listaCategorias;
        ModelState.AddModelError(string.Empty,
          "Ocurrio un error cargando las categorias, revise su conexion a internet");
      }

    }

    private void ConsultarCategoriasSelectEdit(int id)
    {
      com = FabricaComando.GetComandoConsultarCategoriaSelect();
      com.Execute();
      var listaCategoriasSelect = (List<Categoria>)com.GetResult()[0];
      if (listaCategoriasSelect != null)
      {
        listaCategoriasSelect = listaCategoriasSelect.Where(s => s.Nivel < 3 && s.Id != id).ToList();
        ViewBag.MyList = listaCategoriasSelect;
      }
      else
      {
        listaCategoriasSelect = new List<Categoria>();
        ViewBag.MyList = listaCategoriasSelect;
        ModelState.AddModelError(string.Empty,
          "Ocurrio un error cargando las categorias, revise su conexion a internet");
      }
    }

    // ############## Metodos para Validaciones de Vistas #################
    /// <summary>
    /// Metodo que nos permite validar si el nombre existe antes de agregar
    /// </summary>
    private void ValidarError(JObject respuesta)
    {
      if (respuesta.Property("MensajeError") != null)
      {
        ModelState.AddModelError(string.Empty, respuesta["MensajeError"].ToString());
      }
      else
      {
        ModelState.AddModelError(string.Empty, "Ocurrió un error de comunicación");
      }
    }

    private bool ValidarName(String input)
    {
      if (validacion.ValidarCaracteresEspeciales(input) && validacion.ValidarLongitudInputNombreCategoria(input))
      {
        return true;
      }
      ModelState.AddModelError(string.Empty,
        "El nombre de la categoria debe tener al menos 5 caracteres y máximo 20. Sólo se permiten letras.");
      return false;
    }

    private bool ValidarDescription(String input)
    {
      if (validacion.ValidarCaracteresEspeciales(input) && validacion.ValidarLongitudInputDescripcionCategoria(input))
      {
        return true;
      }
      ModelState.AddModelError(string.Empty,
        "La descripcion de la categoria debe tener al menos 5 caracteres y máximo 100. Sólo se permiten letras.");
      return false;
    }
  }
}

BackOffice/BackOffice-COCO-TRIP/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BackOffice_COCO_TRIP.Views.Locations
{
    public class LocationsController : Controller
    {
        // GET: Locations
        public ActionResult Index()
        {
            return View();
        }

        // GET: Locations/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

    // GET: Locations/CreateLocationEvent
    public ActionResult CreateLocationEvent()
        {
            return View();
        }

    // POST: Locations/CreateLocationEvent
    [HttpPost]
        public ActionResult CreateLocationEvent(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    // GET: Locations/ListLocationEvent
    public ActionResult ListLocationEvent()
        {
          return View();
        }

        // POST: Locations/ListLocationEvent
        [HttpPost]
        public ActionResult ListLocationEvent(FormCollection collection)
        {
          try
          {
            // TODO: Add insert logic here

            return RedirectToAction("Index");
          }
          catch
          {
            return View();
          }
        }
    // GET: Locations/Edit/5
    public ActionResult Edit(int id)
            {
                return View();
            }

            // POST: Locations/Edit/5
            [HttpPost]
            public ActionResult Edit(int id, FormCollection collection)
            {
                try
                {
                    // TODO: Add update logic here

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

        // GET: Locations/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Locations/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BackOffice/BackOffice-COCO-TRIP/Views/Locations/CreateLocationEvent.cshtml
@Styles.Render("~/bundles/categoriesCSS")
<div class="card color-texto">
    <div class="container-fluid pad-top">
        <div><h4>Ingrese los datos:</h4></div>
        <hr>
        <form class="form-horizontal">
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="NombreLocalidadCrear" placeholder="Categoría">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 control-label">Descripción</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="DescripcionLoclidadCrear" placeholder="Descripción">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary pull-right">Agregar Categoría</button>
                </div>
            </div>
        </form>
    </div>
</div>

BackOffice/BackOffice-COCO-TRIP/Views/Locations/ListLocationEvent.cshtml
@Styles.Render("~/bundles/categoriesCSS")

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css ">


<div class="card">
    <div class="container-fluid pad-top">
        <div class="color-texto"><h4>Lista de localidades de eventos</h4></div>
        <hr>
        <table width="100%" class="table table-striped table-bordered" id="example" cellspacing="0">
            <thead>
                <tr>

                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Opciones</th>
                    
                </tr>
            </thead>
            <tbody>
                <tr>

                    <td>Lugar</td>
                    <td>lorem ipsum</td>
                    <td>
                        <button type="button" class="btn btn-default circle" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Listar subcategorias">
                            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-default circle ver-categoria" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Ver mas">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>

                        <a class="btn btn-default circle" href="@Url.Action("Edit", "Locations", new { id = 1 })" data-toggle="tooltip"
                           data-placement="top" title="Editar">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>

                    </td>
                   

                </tr>
                <tr>

                    <td>Evento</td>
                    <td>lorem ipsum</td>
                    <td>
                        <button type="button" class="btn btn-default circle" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Listar subcategorias">
                            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-default circle ver-categoria" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Ver mas">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>

                        <a class="btn btn-default circle" href="@Url.Action("Edit", "Categories", new { id = 1 })" data-toggle="tooltip"
                           data-placement="top" title="Editar">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>

                    </td>
                    

                </tr>
                <tr>

                    <td>Turistas</td>
                    <td>lorem ipsum</td>
                    <td>
                        <button type="button" class="btn btn-default circle" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Listar subcategorias">
                            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-default circle ver-categoria" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Ver mas">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                        
                        <a class="btn btn-default circle" href="@Url.Action("Edit", "Categories", new { id = 1 })" data-toggle="tooltip"
                           data-placement="top" title="Editar">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>

                    </td>
                    

                </tr>
            </tbody>
        </table>
    </div>
    
</div>


<!--MODAL-->

<div class="modal fade" id="mostrarCategoria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Detalles de la categoria</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="nombre" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" id="nombre" value="Evento" readonly>
                    </div>
                    <div class="form-group">
                        <label for="descripcion" class="col-form-label">Descripcion:</label>
                        <textarea class="form-control" id="descripcion" readonly>Base sobre la cual surgiran la categorias</textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>



@section scripts {
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js "></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/categoriesJS")
    
    }